mongo:
  prod: mongodb://127.0.0.1:27017
  db: tutorDB
rsa:
  public: |
    -----BEGIN PUBLIC KEY-----
    MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEApygEosp/VTM0sM5Pm+R8
    RDtXd0I6tEEq7zjaZUYRnb7pXYydC5wxYG5doH4XXKxlEn1EgXRNetfE7x6hNo6b
    OCkgOCC2pdrSv2pTaUVrxWJgdtXUzgPHc1z1msRg/rzskSNVa1odJzKIY4GG7MXm
    X9O7SrotNk8PcU8ZQhjlj20tHQDNE1ttUM/mCbq99sl9WvtEtP6t7U7BkGvyQl8x
    XR8Us3MikDi4qkQsuylWaZQ2CTJia535NLX1PjLlYWNlYQrXTOPtfeQZUgB2Twgs
    6Sf2NT2CN09Q8HEJelLHWlYewjwbMh+u0CoA7Mfytq6BxlsVlMAjcIZCzaDZXY6V
    bI7Vx1RN3tq7dVlFxvLgSVv9K/933vrUPbNChyI73opaYBTd6owxW5T5Z6ZRgitE
    LYY7mn7c8K/u/glcC/Use3mZ+MWf0UnLLU/FQmh+nRzhFEoiDpAumQauctTZFEsD
    cvSuToPKI1Y8+zkRFjNtbrwnLl34F+EGDOvkfj5qWJS/AgMBAAE=
    -----END PUBLIC KEY-----
  private: |
    -----BEGIN PRIVATE KEY-----
    MIIG/QIBADANBgkqhkiG9w0BAQEFAASCBucwggbjAgEAAoIBgQCnKASiyn9VMzSw
    zk+b5HxEO1d3Qjq0QSrvONplRhGdvuldjJ0LnDFgbl2gfhdcrGUSfUSBdE1618Tv
    HqE2jps4KSA4ILal2tK/alNpRWvFYmB21dTOA8dzXPWaxGD+vOyRI1VrWh0nMohj
    gYbsxeZf07tKui02Tw9xTxlCGOWPbS0dAM0TW21Qz+YJur32yX1a+0S0/q3tTsGQ
    a/JCXzFdHxSzcyKQOLiqRCy7KVZplDYJMmJrnfk0tfU+MuVhY2VhCtdM4+195BlS
    AHZPCCzpJ/Y1PYI3T1DwcQl6UsdaVh7CPBsyH67QKgDsx/K2roHGWxWUwCNwhkLN
    oNldjpVsjtXHVE3e2rt1WUXG8uBJW/0r/3fe+tQ9s0KHIjveilpgFN3qjDFblPln
    plGCK0Qthjuaftzwr+7+CVwL9Sx7eZn4xZ/RScstT8VCaH6dHOEUSiIOkC6ZBq5y
    1NkUSwNy9K5Og8ojVjz7OREWM21uvCcuXfgX4QYM6+R+PmpYlL8CAwEAAQKCAYAZ
    8VC24JgJOxyZtuC4IIAA1EzrihszpUw/5cz6HCPZHat5BL0i83zeVdgGHqEK6wlM
    vfsHNGu0qGQ80GjTiifLpuZZ5QnejSsENkD30k8QSrJkqc87TMQvGBBY6Cg9oPNT
    m0OYmQXJSEMkCRL4ZcaEEjJmk0/iYTwo/nkRvxdxvnoFSaiKW+Lda0bCinm3zDxp
    BcemEkN1fzGfc9bHjPVLrz/hPKSdSZBaLKEx8w/MQbUZPE6gxoXKM9X6GfVru1Hc
    wwvLmKHnow8MLJE8uHvoPSrnM8ODG80wHBg8DnXUeD9vHb24AXydN5iwNQWn+HGr
    mhpSKWLdzf5FF98o72k2YTe7QPPPJKtad8/S2uzPGBc8gkymU1ju6VnvSvAKlX/l
    LqBqCpVIJnkF6ewEDe4F39vPsZYSlq0/y0IXb/y1nRF7V/Lsf8Srfca7FV986mrX
    T8QP4wSleB+R4f0bJKg/vuUPDFqMDoBfzrJ4boQoVgqIuykSko3OyEpRUUofYaEC
    gcEA5Wni/w2OP8VLgH3hJ6XFTXgcd/jsSAICrDm/vG1CcSdzexokHqCc/NCHC/vG
    Rr5owL6v225QPC89/TWnn7YkNm6oSB3bfYdsmpNjfDn1T1TGmdPdsfYRa9NCZM0V
    HymkZqe8SnrByJ7kxvv+cqRBAgizBSvqLV5IW55yGHj1ln/qJa66dGlfGRvW0dmj
    xo4Dz7Y0fUvdSsCmMupOOB0afOIChsGT3mQQi2Ttz0tAvyFT3sM13PuVJjQKzdqp
    hBGnAoHBALqHHfvxt8eVrx1yEeiAxqkqx5d7LxcJG4/f5LXkZdiRpuGFnMsytXA/
    EWp2FUHK6Eb4t+bVB3VauaIBAl7TzrXWh/Vavzn3WHlXKuU5FfKbHQSZaNzl5+3J
    1KjpzFHfIUKSBavOIoFu5QyD0WiTbVHmoSR7fiBfzML9cwlL0c9V9icMzg/gV6kX
    EMxwL1Swh4zDbckywM7VREkSax5yQAj4l7sJvCx0nvJtecusLJSiuSqUn1pVQ8Ph
    0io//n5XKQKBwQChl03uvUufG4ctAH2hgaBSCvJyhwFXTyM20I5/WK5eKZ2r7iPW
    9ubdJLya8kMc/W2npikUdMVLPzN4sVxaoN8tABDEi1NZPhR/ZKXEkMZ7lIk3PQaB
    HYPz4SB5BAOGqbxFGo0EISdx+onGpyT49z1bA2mlkOMoBasN7bMMDddepMb2t/ZZ
    nQcBFpzfv18eslV47yxVvSQoTT5DyspBuC46HLAO3zcahH0q0nK3epgmiIEc/X9p
    IkRSXoHlscmJXy0CgcB996/9LNGjPOglJ5sGfKktJ5HhMDSuBt2RPW/0kslhB4Q+
    +3/XDmjP5Be74QEcDI7vFxsDDczaqSmCSdIy/jG0RaxNuzo3SF58m6yBXxr+W1iu
    eXgC7lTCFrLCXBo7FEge8ARacXyGEsEmwYLTb/S9AdbDj46vCGN9L7LXjVelAPWa
    i6BBwo0QyV3z4rNkK09vda+X1+m0BPz3qDOlPR0XseKuUrW9BAkvyVUegikdPAN2
    ySYQ2FJKYCARnmQdKHkCgcA8DPDpbN23QQg2mg1519WT7jKFB1XHPvbRYL1YvUCM
    e3WfTud4XPCEtigTbtP9nvG/2+D0V6DY+glg7eOcW9v92Nn7GvzgiJHtTu7cXYs8
    y5H+kanW+MvJvWFppEbZu2NyJmZttO3S6ugj/hALLD4Wn79CxS4HClHOVchGyuZx
    kVQNjFsTkD6GWkqd35V1QG8MyvToxYwyLpo457Ej2zd+ON68Ugul1L68KG2+YnNv
    RCkuE6jfdEb52+0PGPDKeVI=
    -----END PRIVATE KEY-----
